### ISSUE TITLE
ADD A SERVICE OR API instruction

### ISSUE THREAD

**Issue by truevis** [watson-developer-cloud/nests#2]
Suggest to use dashboard to add "Tradeoff Analytics".

**Comment by nfriedly** [comment]
Hi, I'm not sure I understand what you're asking for here; are you saying that we should provide instructions for using the bluemix web interface instead of the cf command line tool for step 5?

> <ol start="5"><li> <p>Create the Tradeoff Analytics service in Bluemix.</p>
>     <pre><code>$ cf create-service tradeoff_analytics standard tradeoff-analytics-service</code></pre></li></ol>

Or are you talking about the "Running Locally" section? (It assumes that you already did the previous instructions to set up bluemix, but we should probably make that explicit....)

**Comment by truevis** [comment]
Suggest to add instructions for using the bluemix web interface.

**Comment by nfriedly** [comment]
OK, I understand. I personally don't think we should add that to the readme -  the command line tools are required for other steps, so I think sticking with them the whole way through is simpler.

However, I'll leave it up to @boazdavid or @germanattanasio to make the final call there.

**Comment by germanattanasio** [comment]
Bluemix will change the way to create and access services. I don't think we should add instructions on how to use Bluemix.

**Comment by bvonhag** [comment]
As German says, we cannot document how to use the Bluemix UI, because it 
will always change. The cf command-line tool is a lowest common 
denominator solution.

Bill von Hagen
Watson Platform Developer Content and Community Manager
IBM Watson Group
email: bvonhag@us.ibm.com | Tel: 412-315-2134
Participant Code for calls: 98397956
